import {time,priceText,quantity,defaultUnit,emptyDates,UNITS,expired} from './domain.js';
import {el,button,field,select,check,modal,closeModal,message,empty,facts} from './dom.js';
export function resumeSourceDraft(draft,ctx){ctx.state.sourceId=draft.source;return edit(null,ctx,false,draft);}
export async function sourceScreen(root,ctx){
  const {state,CONFIG,api,store}=ctx,g=state.generation,user=state.session?.user.id;
  if(!user){root.append(empty('Your Source day','Sign in to manage your catalogue and the work saved on this device.'),button('Sign in',ctx.requireAuth));return ()=>{};}
  if(!CONFIG.sources.length){root.append(empty('Source selection awaits the backend directory','This draft contract cannot discover your Source memberships. The backend operator must supply a documented membership endpoint or approved staging Source choices. No memberships have been inferred.'));return ()=>{};}
  const toolbar=el('div',null,{class:'toolbar'}),chooser=select('Your Source',[['','Select a Source'],...CONFIG.sources.map(s=>[s.id,s.name])],state.sourceId||'');
  chooser.input.addEventListener('change',()=>{state.sourceId=chooser.input.value||null;state.generation++;ctx.refresh();});toolbar.append(chooser.label);root.append(toolbar);
  if(!state.sourceId)return ()=>{};
  const sourceId=state.sourceId;let profile,response;
  try{[profile,response]=await Promise.all([api.rpc('integrity_profile_v1',{source_id:sourceId}),api.page('integrity_catalogue_v1',{source_id:sourceId})]);}
  catch(e){if(ctx.guard(g))root.append(empty('Source access could not be confirmed','No private catalogue is displayed. Your saved drafts remain scoped to the original account and Source.'));return ()=>{};}
  if(!ctx.guard(g))return ()=>{};
  const p=profile.data,offers=response.data.items;
  await store.put('server',user,sourceId,'catalogue',{items:offers,serverTime:response.server_time});
  const drafts=await store.list('drafts',user,sourceId);if(!ctx.guard(g))return ()=>{};
  root.append(button(p.name,()=>profileForm(p,ctx)),el('p',p.active?'Source active':'Source paused · your catalogue remains manageable'),el('p','Current role is checked by the server on every command. A role-discovery endpoint is still needed for complete viewer controls.',{class:'muted'}));
  toolbar.append(button('Add a new batch',()=>edit(null,ctx),'primary'),button('Export stock/history',()=>exportCatalogue(offers,p,ctx)),button('Print current stock',()=>printStock(offers,p)));
  const cards=el('div',null,{class:'cards'});root.append(cards);
  for(const o of offers){const c=el('article',null,{class:'card'}),saved=drafts.find(d=>d.id===o.lot_id),actions=el('div',null,{class:'actions'});
    c.append(el('p',o.classification.toUpperCase(),{class:'eyebrow'}),el('h2',o.food_name),el('p',`${o.physical_quantity??'Unknown'} ${o.unit} · ${priceText(o.price,o.unit)}`),el('p',expired(o,api.now())||o.visibility!=='public'||!o.source_active?'Not currently published—confirm, change or retire':`Declared ${time(o.availability_confirmed_at)}`),el('p',`Held ${o.held_quantity} · available ${o.claimable_quantity} ${o.unit}`));
    if(saved)c.append(el('p','Saved on this device · unpublished changes',{class:'badge'}));
    if(saved&&saved.baseRevision!==o.revision)c.append(el('p','Server revision changed. Review both versions before publishing.',{class:'error'}));
    actions.append(button(saved?'Resume draft':'Change',()=>edit(o,ctx)),button('Same batch · reconfirm',()=>reconfirm(o,ctx)),button('New batch',()=>edit(o,ctx,true)),button('Sold out',()=>countZero(o,ctx)),button('Retire',()=>reason('Retire this offer',async r=>ctx.command('integrity_withdraw_v1',{source_id:sourceId,offer_id:o.id,expected_revision:o.revision,reason:r},sourceId))),button('Evidence',()=>evidenceForm(o,ctx)));c.append(actions);cards.append(c);
  }
  for(const d of drafts.filter(d=>!offers.some(o=>o.lot_id===d.id))){const c=el('article',null,{class:'card'});c.append(el('h2',d.foodName||'Unpublished batch'),el('p','Saved on this device'),button('Resume draft',()=>edit(null,ctx,false,d)));cards.append(c);}
  if(!offers.length&&!drafts.length)cards.append(empty('No catalogue items on this page','Expired batches remain manageable when returned by the member catalogue.'));
  if(response.data.next_cursor)root.append(el('p','More catalogue records exist. This first implementation displays 50; complete member pagination remains a release gate.'));
  return ()=>{};
}
function dateField(label,value){const f=field(label,'','datetime-local');if(value){const d=new Date(value);f.input.value=new Date(+d-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}return f;}
function iso(value){if(!value)return null;const d=new Date(value);if(Number.isNaN(+d))throw Error('Invalid date.');return d.toISOString();}
async function edit(offer,ctx,newBatch=false,resume=null){
  const {state,store,api,CONFIG}=ctx,user=state.session.user.id,source=state.sourceId,g=state.generation;
  if(offer&&!offer.lot_id&&!newBatch){message('This legacy offer needs owner/admin activation and reviewed historical claims before publication.');return;}
  const id=resume?.id||(newBatch||!offer?crypto.randomUUID():offer.lot_id);
  let draft=resume||await store.get('drafts',user,source,id);
  if(!ctx.guard(g))return;
  const initial=draft?.form||{foodId:offer?.food_id||'',unit:offer?.unit||'each',quantity:offer?.physical_quantity||'',price:offer?.price||{status:'unknown',amount:null,currency:'GBP',basis:null,bundle_quantity:null,package_quantity:null,package_unit:null},lifecycle:offer?.lifecycle==='retired'?'ready':offer?.lifecycle||'ready',pressure:offer?.pressure||'normal',visibility:offer?.visibility||'public',reservable:offer?.reservable||false,listingExpiresAt:null,collectionStart:offer?.collection_start||null,collectionEnd:offer?.collection_end||null,note:'',dates:newBatch?emptyDates():offer?.physical_dates||emptyDates()};
  draft=draft||{localVersion:0,baseRevision:offer&&!newBatch?offer.revision:0,lotId:offer&&!newBatch?offer.lot_id:null,foodName:offer?.food_name||'',createId:crypto.randomUUID(),publishId:crypto.randomUUID(),form:initial};
  const box=el('div'),form=el('div',null,{class:'form-grid'}),foods=[...CONFIG.foods];if(offer&&!foods.some(f=>f.id===offer.food_id))foods.push({id:offer.food_id,name:offer.food_name});
  const food=select('Food',[['','Choose a food'],...foods.map(f=>[f.id,f.name])],initial.foodId),unit=select('How is this counted?',UNITS,initial.unit),qty=field('Physical quantity',initial.quantity),status=select('Price',['unknown','free','priced'].map(x=>[x,x==='unknown'?'Price not supplied':x==='free'?'Free':'Set price']),initial.price.status),amount=field('Amount (£)',initial.price.amount||''),basis=select('Price basis',[['per_unit','Per counted unit'],['per_kg','Per kg'],['per_litre','Per litre'],['per_lot','Per whole batch'],['bundle','Bundle']],initial.price.basis||'per_unit'),bundle=field('Units in the bundle',initial.price.bundle_quantity||''),pack=field('Package quantity (optional)',initial.price.package_quantity||''),packUnit=select('Package unit',[['','Unknown'],...UNITS],initial.price.package_unit||''),lifecycle=select('Physical stage',[['ready','Ready'],['growing','Growing'],['at_sea','At sea']],initial.lifecycle),pressure=select('Availability pressure',[['normal','Normal'],['surplus','Surplus'],['needs_moving','Needs moving']],initial.pressure),visibility=select('Visibility',[['public','Public'],['members','Source members']],initial.visibility),reservable=check('Allow hold requests',initial.reservable),expires=dateField('Declaration expires (your local time)',initial.listingExpiresAt),start=dateField('Collection from (your local time)',initial.collectionStart),end=dateField('Collection until (your local time)',initial.collectionEnd),note=field('Note',initial.note,'textarea');
  const saved=el('p','Changes have not yet been saved.'),preview=el('p',null,{class:'price'}),fields=[food,unit,qty,status,amount,basis,bundle,pack,packUnit,lifecycle,pressure,visibility,expires,start,end,note];
  for(const f of fields)form.append(f.label);form.append(reservable.label);box.append(el('p',draft.lotId?'Same batch · physical dates are preserved':'New batch · physical dates start unknown'),form);
  if(!draft.lotId&&!foods.length)box.append(el('p','The backend food directory has not been supplied. New food selection is unavailable.',{class:'error'}));
  food.input.disabled=Boolean(draft.lotId);unit.input.disabled=Boolean(draft.lotId);
  const dates=el('details'),dateInputs={};dates.append(el('summary','Physical dates, handling and allergens'));
  for(const [key,label]of [['harvested_at','Harvested'],['landed_at','Landed'],['baked_at','Baked'],['packed_at','Packed']]){const f=dateField(label+' (your local time)',initial.dates[key]);f.input.disabled=Boolean(draft.lotId);dates.append(f.label);dateInputs[key]=f;}
  const handling=field('Handling',initial.dates.handling,'textarea'),allergens=field('Allergen information',initial.dates.allergen_information,'textarea');handling.input.disabled=allergens.input.disabled=Boolean(draft.lotId);dates.append(handling.label,allergens.label);box.append(dates,preview,saved);
  function snapshot(){return {foodId:food.input.value,unit:unit.input.value,quantity:qty.input.value,price:{status:status.input.value,amount:status.input.value==='priced'?amount.input.value:status.input.value==='free'?'0':null,currency:'GBP',basis:status.input.value==='priced'?basis.input.value:null,bundle_quantity:status.input.value==='priced'&&basis.input.value==='bundle'?bundle.input.value:null,package_quantity:pack.input.value||null,package_unit:packUnit.input.value||null},lifecycle:lifecycle.input.value,pressure:pressure.input.value,visibility:visibility.input.value,reservable:reservable.input.checked,listingExpiresAt:iso(expires.input.value),collectionStart:iso(start.input.value),collectionEnd:iso(end.input.value),note:note.input.value,dates:draft.lotId?initial.dates:{...initial.dates,...Object.fromEntries(Object.entries(dateInputs).map(([k,f])=>[k,iso(f.input.value)])),handling:handling.input.value||null,allergen_information:allergens.input.value||null}};}
  let saving=Promise.resolve(),closed=false,saveFailed=false;
  function save(){const value=snapshot();saving=saving.then(async()=>{if(!ctx.guard(g))return;draft=await store.saveDraft(user,source,id,{...draft,form:value,foodName:foods.find(f=>f.id===value.foodId)?.name||draft.foodName},draft.localVersion);saveFailed=false;if(!closed)saved.textContent='Saved on this device';}).catch(e=>{saveFailed=true;if(!closed)saved.textContent=e.message;});return saving;}
  function change(){try{const f=snapshot();preview.textContent=`${f.quantity||'?'} ${draft.foodName||'food'} · ${priceText(f.price,f.unit)} · ${f.pressure}`;}catch{preview.textContent='Complete the price and quantity for a preview.';}saved.textContent='Saving on this device…';save();}
  form.addEventListener('input',change);dates.addEventListener('input',change);food.input.addEventListener('change',()=>{if(!draft.lotId){unit.input.value=defaultUnit(foods.find(f=>f.id===food.input.value)?.name||'');change();}});
  if(offer&&!newBatch&&draft.baseRevision!==offer.revision){box.append(el('p','Conflict: the Source changed after this draft was saved. Publishing is blocked until you review the new stock and terms.',{class:'error'}),button('Review current server record',()=>modal('Current server state',el('pre',JSON.stringify(offer,null,2)))));}
  box.append(button('Save on this device',save),button('Review & publish',async()=>{
    await save();await saving;if(saveFailed)throw Error('Device save failed. Publication was not started.');if(!ctx.guard(g))return;
    const f=draft.form;quantity(f.quantity,f.unit);if(!f.foodId||!f.listingExpiresAt)throw Error('Choose a food and declaration expiry.');if(Date.parse(f.listingExpiresAt)<=api.now())throw Error('Choose a future declaration expiry.');
    if(offer&&!newBatch&&draft.baseRevision!==offer.revision)throw Error('Resolve the revision conflict before publishing.');
    const review=el('div');review.append(el('p',`${f.quantity} ${f.unit} ${draft.foodName} · ${priceText(f.price,f.unit)} · ${f.pressure}`),el('p','Confirm your physical count and collection window now. Any server revision conflict will preserve this draft.'),button('Confirm publication',async()=>{
      if(!ctx.guard(g))return;
      if(!draft.lotId){const result=await ctx.command('integrity_create_lot_v1',{source_id:source,food_id:f.foodId,unit:f.unit,physical_dates:f.dates},source,{operationId:draft.createId});if(!result)return;draft=await store.saveDraft(user,source,id,{...draft,lotId:result.lot_id,baseRevision:result.revision},draft.localVersion);}
      const result=await ctx.command('integrity_publish_v1',{source_id:source,lot_id:draft.lotId,expected_revision:draft.baseRevision,physical_quantity:f.quantity,price:f.price,lifecycle:f.lifecycle,pressure:f.pressure,visibility:f.visibility,reservable:f.reservable,listing_expires_at:f.listingExpiresAt,collection_start:f.collectionStart,collection_end:f.collectionEnd,note:f.note||null},source,{operationId:draft.publishId});
      if(result){await store.remove('drafts',user,source,id);closeModal();await ctx.refresh();message('Published · server acknowledgement received.');}
    },'primary'));modal('Confirm your declaration',review);
  },'primary'));modal('Your batch',box,()=>{closed=true;});
}
function reconfirm(o,ctx){const box=el('div'),expiry=dateField('New declaration expiry (your local time)',null);box.append(el('p',`Reconfirm this same batch: ${o.physical_quantity} ${o.unit}. Harvest, landing and bake dates stay unchanged.`),expiry.label,button('Confirm unchanged stock',async()=>{const expires=iso(expiry.input.value);if(!expires)throw Error('Choose an expiry.');await ctx.command('integrity_reconfirm_v1',{source_id:o.source_id,offer_id:o.id,expected_revision:o.revision,listing_expires_at:expires},o.source_id);closeModal();},'primary'));modal('Same batch',box);}
function countZero(o,ctx){reason('Count physical stock as zero',r=>ctx.command('integrity_reconcile_stock_v1',{source_id:o.source_id,offer_id:o.id,expected_revision:o.revision,counted_quantity:'0',count_observed_at:new Date(ctx.api.now()).toISOString(),reason:r},o.source_id));}
function reason(title,action){const box=el('div'),f=field('Reason','','textarea');box.append(f.label,button('Confirm',async()=>{if(!f.input.value.trim())throw Error('Provide a reason.');await action(f.input.value);closeModal();},'primary'));modal(title,box);}
function profileForm(p,ctx){const box=el('div'),fields={};for(const [key,name]of [['name','Business name'],['legal_name','Legal name'],['description','Description'],['public_email','Public email'],['public_phone','Public phone'],['contact_url','Website'],['address_line','Address'],['locality','Locality'],['postcode','Postcode'],['collection_notes','Collection instructions']]){fields[key]=field(name,p[key]||'');box.append(fields[key].label);}
  box.append(el('p','Updating your account email is separate from Source identity. Signup does not verify this business.'),button('Save profile',async()=>{const patch=Object.fromEntries(Object.entries(fields).map(([k,f])=>[k,f.input.value||null]));await ctx.command('integrity_update_profile_v1',{source_id:p.source_id,expected_revision:p.revision,patch},p.source_id);closeModal();},'primary'),button(p.active?'Pause Source':'Reactivate Source',async()=>{await ctx.command('integrity_set_active_v1',{source_id:p.source_id,expected_revision:p.revision,active:!p.active},p.source_id);closeModal();}));modal('Source profile',box);}
async function evidenceForm(o,ctx){
  if(!ctx.api.health?.capabilities.evidence_upload){message('Evidence uploads are currently unavailable.');return;}
  const {store,state,api,CONFIG}=ctx,user=state.session.user.id,source=o.source_id,box=el('div'),file=field('JPEG, PNG or WebP photo (up to 10 MB)','','file'),caption=field('Caption'),observed=dateField('When was it observed? (optional, your local time)',null),preview=el('div');file.input.accept='image/jpeg,image/png,image/webp';
  let url=null;file.input.addEventListener('change',()=>{if(url)URL.revokeObjectURL(url);preview.replaceChildren();const f=file.input.files[0];if(f&&['image/jpeg','image/png','image/webp'].includes(f.type)){url=URL.createObjectURL(f);preview.append(el('img',null,{src:url,alt:'Private evidence preview',class:'evidence-image'}));}});
  box.append(el('p','Preview for personal information before uploading. Sharing is a separate step after server sanitisation. HEIC: export a JPEG first. PDFs are not accepted by this photo flow.'),file.label,preview,caption.label,observed.label,button('Save file privately on this device',async()=>{
    const f=file.input.files[0];if(!f||f.size>10485760||!['image/jpeg','image/png','image/webp'].includes(f.type))throw Error('Choose a JPEG, PNG or WebP image under 10 MB.');
    const id=crypto.randomUUID(),hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',await f.arrayBuffer()))].map(n=>n.toString(16).padStart(2,'0')).join('');
    await store.put('files',user,source,id,{blob:f,eventId:o.latest_event_id,caption:caption.input.value||null,observedAt:iso(observed.input.value),checksum:hash,beginId:crypto.randomUUID(),finalizeId:crypto.randomUUID(),publishId:crypto.randomUUID(),status:'pending'});
    closeModal();message('File saved on this device · evidence pending. Reopen Evidence to send.');
  },'primary'));
  const saved=await store.list('files',user,source);
  for(const record of saved.filter(r=>r.eventId===o.latest_event_id)){const c=el('article',null,{class:'card'});c.append(el('h3',record.caption||'Saved photo'),el('p',record.status==='linked'?'Private evidence linked':'Evidence pending'),button('Upload / retry exact attachment',async()=>{
    if(state.session?.user.id!==user)throw Error('Account changed.');
    const begin=await ctx.command('integrity_begin_evidence_v1',{source_id:source,event_id:record.eventId,attachment_id:record.id,media_type:record.blob.type,bytes:record.blob.size,checksum_sha256:record.checksum,caption:record.caption,declared_observed_at:record.observedAt},source,{operationId:record.beginId});if(!begin)return;
    const current=await api.rpc('integrity_evidence_status_v1',{source_id:source,attachment_id:record.id});
    if(current.data.status==='pending'){
      const r=await fetch(`${CONFIG.url}/functions/v1/integrity-evidence/upload/${record.id}`,{method:'POST',credentials:'omit',cache:'no-store',referrerPolicy:'no-referrer',signal:AbortSignal.timeout(95000),headers:{apikey:CONFIG.publishableKey,Authorization:'Bearer '+state.session.access_token,'x-source-id':source,'Content-Type':record.blob.type},body:record.blob});
      if(!r.ok)throw Error('Upload not confirmed. Saved file retained for retry.');
    }
    const result=await ctx.command('integrity_finalize_evidence_v1',{source_id:source,attachment_id:record.id},source,{operationId:record.finalizeId});if(!result)return;
    record.status=result.status;await store.put('files',user,source,record.id,record);closeModal();message('Evidence linked privately. Reopen Evidence to preview the sanitised image before sharing.');
  }));
    if(record.status==='linked')c.append(button('Preview sanitised photo & choose sharing',async()=>{
      const blob=await api.evidence(record.id),imageUrl=URL.createObjectURL(blob),confirm=el('div');confirm.append(el('img',null,{src:imageUrl,alt:record.caption||'Sanitised evidence',class:'evidence-image'}),el('p','Check this image for personal information. Sharing does not verify its contents. Downloaded copies cannot be recalled.'),button('Share this photo publicly',async()=>{await ctx.command('integrity_publish_evidence_v1',{source_id:source,attachment_id:record.id},source,{operationId:record.publishId});closeModal();},'primary'),button('Withdraw public sharing',()=>reason('Withdraw evidence',r=>ctx.command('integrity_withdraw_evidence_v1',{source_id:source,attachment_id:record.id,reason:r},source))));modal('Review public sharing',confirm,()=>URL.revokeObjectURL(imageUrl));
    }));box.append(c);
  }
  modal('Evidence for '+o.food_name,box,()=>{if(url)URL.revokeObjectURL(url);});
}
function exportCatalogue(offers,p,ctx){const data={schema:'provision-member-catalogue/1.0.0-draft.1',contract_sha256:ctx.CONFIG.checksum,server_time:ctx.api.lastSynced,source:p,scope:'First catalogue page only; history export remains pending',offers},url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=el('a',null,{href:url,download:'provision-source-stock.json'});a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function printStock(offers,p){const box=el('div');box.append(el('h2',p.name),el('p','STAGING / TEST DATA · not a real stock sign'));for(const o of offers)box.append(el('p',`${o.food_name} · ${o.physical_quantity??'Unknown'} ${o.unit} · ${priceText(o.price,o.unit)}`));box.append(button('Print',()=>window.print()));modal('Current stock',box);}
